# Generated by Django 4.2.7 on 2025-07-10 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom du produit')),
                ('active_ingredient', models.CharField(max_length=255, verbose_name='Principe actif')),
                ('dosage', models.CharField(max_length=100, verbose_name='Dosage')),
                ('form', models.CharField(max_length=100, verbose_name='Forme')),
                ('therapeutic_area', models.CharField(max_length=200, verbose_name='Zone thérapeutique')),
                ('status', models.CharField(choices=[('commercialise', 'Commercialisé'), ('developpement', 'En développement'), ('arrete', 'Arrêté')], default='developpement', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variation_type', models.CharField(choices=[('type_ia', 'Type IA'), ('type_ib', 'Type IB'), ('type_ii', 'Type II')], max_length=10)),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('submission_date', models.DateField(verbose_name='Date de soumission')),
                ('approval_date', models.DateField(blank=True, null=True, verbose_name="Date d'approbation")),
                ('status', models.CharField(choices=[('soumis', 'Soumis'), ('en_cours', 'En cours'), ('approuve', 'Approuvé'), ('rejete', 'Rejeté')], default='soumis', max_length=20)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='products.product')),
            ],
            options={
                'verbose_name': 'Variation produit',
                'verbose_name_plural': 'Variations produits',
                'ordering': ['-submission_date'],
            },
        ),
        migrations.CreateModel(
            name='ManufacturingSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100, verbose_name='Pays')),
                ('city', models.CharField(max_length=100, verbose_name='Ville')),
                ('site_name', models.CharField(max_length=255, verbose_name='Nom du site')),
                ('gmp_certified', models.BooleanField(default=False, verbose_name='Certifié GMP')),
                ('gmp_expiry', models.DateField(blank=True, null=True, verbose_name='Expiration GMP')),
                ('last_audit', models.DateField(blank=True, null=True, verbose_name='Dernier audit')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='products.product')),
            ],
            options={
                'verbose_name': 'Site de fabrication',
                'verbose_name_plural': 'Sites de fabrication',
            },
        ),
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=3, verbose_name='Code pays')),
                ('amm_number', models.CharField(max_length=100, verbose_name='Numéro AMM')),
                ('approval_date', models.DateField(verbose_name="Date d'approbation")),
                ('renewal_date', models.DateField(verbose_name='Date de renouvellement')),
                ('ctd_dossier_complete', models.BooleanField(default=False, verbose_name='Dossier CTD complet')),
                ('gmp_certificate', models.BooleanField(default=False, verbose_name='Certificat GMP')),
                ('inspection_report', models.BooleanField(default=False, verbose_name="Rapport d'inspection")),
                ('rcp_etiquetage', models.BooleanField(default=False, verbose_name='RCP et étiquetage')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='products.product')),
            ],
            options={
                'verbose_name': 'Spécification produit',
                'verbose_name_plural': 'Spécifications produits',
                'unique_together': {('product', 'country_code')},
            },
        ),
    ]
