# Generated by Django 4.2.7 on 2025-08-04 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rawdocs', '0010_userprofile'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='additional_annotations',
            field=models.JSONField(blank=True, default=dict, verbose_name='Annotations supplémentaires'),
        ),
        migrations.AddField(
            model_name='product',
            name='source_document',
            field=models.ForeignKey(blank=True, help_text='Document original ayant généré ce produit', null=True, on_delete=django.db.models.deletion.SET_NULL, to='rawdocs.rawdocument', verbose_name='Document source'),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='additional_annotations',
            field=models.JSONField(blank=True, default=dict, verbose_name='Annotations supplémentaires'),
        ),
    ]
