# Generated by Django 5.2.5 on 2025-08-14 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_additional_annotations_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('google_drive', 'Google Drive'), ('onedrive', 'Microsoft OneDrive'), ('sharepoint', 'SharePoint'), ('dropbox', 'Dropbox'), ('box', 'Box')], max_length=20)),
                ('connection_name', models.CharField(max_length=100)),
                ('encrypted_access_token', models.BinaryField()),
                ('data_residency_eu', models.BooleanField(default=False)),
                ('scc_agreement', models.BooleanField(default=False)),
                ('dpa_signed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('audit_log', models.JSONField(default=dict)),
                ('data_subjects_categories', models.JSONField(default=list, help_text='Catégories de personnes concernées')),
                ('sub_processors', models.JSONField(default=list, help_text='Liste des sous-traitants de second rang')),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('encrypted_refresh_token', models.BinaryField(blank=True, null=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('data_subject_information_method', models.CharField(blank=True, max_length=200)),
                ('privacy_notice_provider', models.CharField(choices=[('client', 'Client LFB'), ('provider', 'Fournisseur Cloud'), ('both', 'Les deux')], default='client', max_length=100)),
                ('technical_measures', models.JSONField(default=dict, help_text='Mesures techniques de sécurité')),
                ('organizational_measures', models.JSONField(default=dict, help_text='Mesures organisationnelles')),
                ('transfers_outside_eu', models.BooleanField(default=False)),
                ('transfer_countries', models.JSONField(default=list, help_text='Pays de transfert')),
                ('transfer_safeguards', models.CharField(blank=True, choices=[('adequacy_decision', "Décision d'adéquation"), ('scc', 'Clauses Contractuelles Types'), ('bcr', 'Binding Corporate Rules'), ('derogation', 'Dérogation')], max_length=100)),
                ('rgpd_compliance_validated', models.BooleanField(default=False)),
                ('rgpd_validation_date', models.DateTimeField(blank=True, null=True)),
                ('rgpd_validator', models.CharField(blank=True, max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cloud_connections', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductECTDFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('ectd_section', models.CharField(blank=True, max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('cloud_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.cloudconnection')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ectd_files', to='products.product')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
