# Generated by Django 5.2.3 on 2025-07-23 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expert", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expertlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("annotation_validated", "Annotation validée"),
                    ("annotation_rejected", "Annotation rejetée"),
                    ("annotation_modified", "Annotation modifiée"),
                    ("annotation_deleted", "Annotation supprimée"),
                    ("annotation_created", "Annotation créée"),
                    ("validation_undone", "Validation annulée"),
                    ("document_reviewed", "Document révisé"),
                    ("sentence_reviewed", "Phrase révisée"),
                    ("annotation_type_created", "Type d'annotation créé"),
                    (
                        "document_validated_product_created",
                        "Document validé et produit créé",
                    ),
                ],
                max_length=60,
            ),
        ),
    ]
