# Generated by Django 5.2.3 on 2025-09-01 02:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0003_alter_expertlog_action'),
        ('rawdocs', '0016_rawdocument_expert_validated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertDelta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('delta_type', models.CharField(choices=[('relation_added', 'Relation ajoutée'), ('relation_modified', 'Relation modifiée'), ('relation_removed', 'Relation supprimée'), ('entity_added', 'Entité ajoutée'), ('entity_modified', 'Entité modifiée'), ('qa_added', 'Q&A ajoutée'), ('qa_corrected', 'Q&A corrigée'), ('summary_corrected', 'Résumé corrigé')], max_length=50)),
                ('ai_version', models.JSONField(help_text="Version générée par l'IA avant correction")),
                ('expert_version', models.JSONField(help_text="Version corrigée par l'expert")),
                ('context', models.JSONField(default=dict, help_text='Contexte additionnel (document_summary, entity_context, etc.)')),
                ('confidence_before', models.FloatField(blank=True, help_text="Confiance de l'IA avant correction (0.0-1.0)", null=True)),
                ('expert_rating', models.IntegerField(blank=True, choices=[(1, '1/5'), (2, '2/5'), (3, '3/5'), (4, '4/5'), (5, '5/5')], help_text="Qualité de la correction selon l'expert (1-5)", null=True)),
                ('is_validated', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('reused_count', models.IntegerField(default=0, help_text='Nombre de fois que cette correction a été réutilisée')),
                ('last_reused', models.DateTimeField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expert_deltas', to='rawdocs.rawdocument')),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['document', 'delta_type'], name='expert_expe_documen_305844_idx'), models.Index(fields=['expert', 'created_at'], name='expert_expe_expert__b42b2a_idx'), models.Index(fields=['is_active', 'is_validated'], name='expert_expe_is_acti_be9251_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExpertLearningStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(blank=True, max_length=100)),
                ('total_corrections', models.IntegerField(default=0)),
                ('relations_improved', models.IntegerField(default=0)),
                ('qa_improved', models.IntegerField(default=0)),
                ('avg_expert_rating', models.FloatField(default=0.0)),
                ('corrections_reused', models.IntegerField(default=0)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('expert', 'document_type', 'period_start')},
            },
        ),
    ]
