# Generated by Django 5.2.3 on 2025-07-24 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('rawdocs', '0010_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='source_document',
            field=models.ForeignKey(blank=True, help_text='Document original ayant généré ce produit', null=True, on_delete=django.db.models.deletion.SET_NULL, to='rawdocs.rawdocument', verbose_name='Document source'),
        ),
    ]
