# Generated by Django 4.2.7 on 2025-07-29 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_product_source_document'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reportheatmap',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='reportheatmap',
            name='product',
        ),
        migrations.DeleteModel(
            name='ReportKPI',
        ),
        migrations.RemoveField(
            model_name='reportsubmission',
            name='product',
        ),
        migrations.DeleteModel(
            name='ReportHeatmap',
        ),
        migrations.DeleteModel(
            name='ReportSubmission',
        ),
    ]
