# Generated by Django 5.2.3 on 2025-07-31 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_alter_reportheatmap_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='additional_annotations',
            field=models.JSONField(blank=True, default=dict, verbose_name='Annotations supplémentaires'),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='additional_annotations',
            field=models.JSONField(blank=True, default=dict, verbose_name='Annotations supplémentaires'),
        ),
    ]
