# Generated by Django 4.2.7 on 2025-08-04 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_product_additional_annotations_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='documenttranslation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='documenttranslation',
            name='original_document',
        ),
        migrations.AlterUniqueTogether(
            name='documentversion',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='documentversion',
            name='document',
        ),
        migrations.RemoveField(
            model_name='manufacturingsite',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='source_document',
        ),
        migrations.AlterUniqueTogether(
            name='productspecification',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='productspecification',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productvariation',
            name='product',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='DocumentCategory',
        ),
        migrations.DeleteModel(
            name='DocumentTranslation',
        ),
        migrations.DeleteModel(
            name='DocumentVersion',
        ),
        migrations.DeleteModel(
            name='ManufacturingSite',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductSpecification',
        ),
        migrations.DeleteModel(
            name='ProductVariation',
        ),
        migrations.DeleteModel(
            name='RegulatoryAuthority',
        ),
    ]
