# Generated by Django 5.2.4 on 2025-07-24 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CTDModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('M1', 'Module 1 - Administrative Information'), ('M2', 'Module 2 - Summaries'), ('M3', 'Module 3 - Quality'), ('M4', 'Module 4 - Non-clinical Study Reports'), ('M5', 'Module 5 - Clinical Study Reports')], max_length=10, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CTDSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='ctd_submission.ctdmodule')),
                ('parent_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ctd_submission.ctdsection')),
            ],
            options={
                'ordering': ['module', 'order', 'code'],
                'unique_together': {('module', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('document_type', models.CharField(choices=[('pdf', 'PDF Document'), ('docx', 'Word Document'), ('xlsx', 'Excel Spreadsheet'), ('form', 'Formulaire Web')], max_length=10)),
                ('content_extracted', models.JSONField(blank=True, default=dict)),
                ('template_data', models.JSONField(blank=True, default=dict)),
                ('is_template_generated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='ctd_submission.ctdsection')),
            ],
        ),
        migrations.CreateModel(
            name='AIAnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence_score', models.FloatField(default=0.0)),
                ('analysis_details', models.JSONField(default=dict)),
                ('keywords_found', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('suggested_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctd_submission.ctdmodule')),
                ('suggested_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctd_submission.ctdsection')),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analysis', to='ctd_submission.document')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('region', models.CharField(choices=[('EU', 'Union Européenne (EMA)'), ('US', 'États-Unis (FDA)'), ('CA', 'Canada (Health Canada)'), ('UK', 'Royaume-Uni (MHRA)')], max_length=10)),
                ('submission_type', models.CharField(max_length=100)),
                ('variation_type', models.CharField(blank=True, max_length=100)),
                ('change_description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'En cours'), ('completed', 'Completed'), ('submitted', 'Submitted')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='ctd_submission.submission'),
        ),
        migrations.CreateModel(
            name='TemplateField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('field_label', models.CharField(max_length=200)),
                ('field_type', models.CharField(choices=[('text', 'Text Field'), ('textarea', 'Text Area'), ('select', 'Select Dropdown'), ('checkbox', 'Checkbox'), ('number', 'Number Field'), ('date', 'Date Field')], default='text', max_length=20)),
                ('field_value', models.TextField(blank=True)),
                ('field_options', models.JSONField(blank=True, default=list)),
                ('is_required', models.BooleanField(default=False)),
                ('row_number', models.PositiveIntegerField(default=0)),
                ('column_number', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_fields', to='ctd_submission.document')),
            ],
            options={
                'ordering': ['row_number', 'column_number'],
            },
        ),
    ]
