# Generated by Django 5.2.4 on 2025-07-24 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctd_submission', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='ctd_submission.ctdsection'),
        ),
    ]
