# Generated by Django 5.2.4 on 2025-07-24 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ctd_submission", "0002_alter_document_section"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aianalysisresult",
            options={
                "verbose_name": "Résultat d'analyse IA",
                "verbose_name_plural": "Résultats d'analyses IA",
            },
        ),
        migrations.AddField(
            model_name="aianalysisresult",
            name="analysis_status",
            field=models.CharField(
                choices=[
                    ("success", "Analyse réussie"),
                    ("partial", "Analyse partielle"),
                    ("failed", "Analyse échouée"),
                ],
                default="failed",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="aianalysisresult",
            name="error_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="aianalysisresult",
            name="suggested_module",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ctd_submission.ctdmodule",
            ),
        ),
        migrations.AlterField(
            model_name="aianalysisresult",
            name="suggested_section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ctd_submission.ctdsection",
            ),
        ),
    ]
