# Generated by Django 5.2.4 on 2025-07-24 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ctd_submission", "0003_alter_aianalysisresult_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aianalysisresult",
            options={},
        ),
        migrations.RemoveField(
            model_name="aianalysisresult",
            name="analysis_status",
        ),
        migrations.RemoveField(
            model_name="aianalysisresult",
            name="error_message",
        ),
        migrations.AlterField(
            model_name="aianalysisresult",
            name="suggested_module",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="ctd_submission.ctdmodule",
            ),
        ),
        migrations.AlterField(
            model_name="aianalysisresult",
            name="suggested_section",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="ctd_submission.ctdsection",
            ),
            preserve_default=False,
        ),
    ]
