# Generated by Django 5.2.4 on 2025-07-28 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ctd_submission", "0005_editingsession_documentversion"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aianalysisresult",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="ctdmodule",
            options={"ordering": ["code"]},
        ),
        migrations.AlterModelOptions(
            name="document",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="submission",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="aianalysisresult",
            name="analysis_method",
            field=models.CharField(
                choices=[
                    ("keyword_matching", "Correspondance de mots-clés"),
                    ("mistral_ai", "Analyse Mistral AI"),
                    ("tfidf_cosine", "TF-IDF et similarité cosinus"),
                    ("nltk_nlp", "Traitement NLP avec NLTK"),
                    ("regex_patterns", "Patterns d'expressions régulières"),
                ],
                default="keyword_matching",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="aianalysisresult",
            name="processing_time",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="aianalysisresult",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="document",
            name="extraction_status",
            field=models.CharField(
                choices=[
                    ("pending", "En attente"),
                    ("processing", "En cours"),
                    ("completed", "Terminé"),
                    ("failed", "Échoué"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="editingsession",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="editingsession",
            name="user_agent",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="submission",
            name="auto_analyze_documents",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="submission",
            name="notify_on_analysis",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="templatefield",
            name="help_text",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="templatefield",
            name="placeholder",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="templatefield",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="templatefield",
            name="validation_pattern",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="aianalysisresult",
            name="suggested_module",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="ctd_submission.ctdmodule",
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="submission_type",
            field=models.CharField(
                choices=[
                    ("MAA", "MAA - Marketing Authorisation Application"),
                    ("Variation", "Variation"),
                    ("Extension", "Extension"),
                    ("Renewal", "Renewal"),
                ],
                default="MAA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="templatefield",
            name="field_type",
            field=models.CharField(
                choices=[
                    ("text", "Text Field"),
                    ("textarea", "Text Area"),
                    ("select", "Select Dropdown"),
                    ("checkbox", "Checkbox"),
                    ("number", "Number Field"),
                    ("date", "Date Field"),
                    ("email", "Email Field"),
                    ("url", "URL Field"),
                ],
                default="text",
                max_length=20,
            ),
        ),
    ]
