# Generated by Django 5.2.4 on 2025-07-28 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ctd_submission", "0006_alter_aianalysisresult_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aianalysisresult",
            options={},
        ),
        migrations.AlterModelOptions(
            name="ctdmodule",
            options={},
        ),
        migrations.AlterModelOptions(
            name="document",
            options={},
        ),
        migrations.AlterModelOptions(
            name="submission",
            options={},
        ),
        migrations.RemoveField(
            model_name="aianalysisresult",
            name="analysis_method",
        ),
        migrations.RemoveField(
            model_name="aianalysisresult",
            name="processing_time",
        ),
        migrations.RemoveField(
            model_name="aianalysisresult",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="document",
            name="extraction_status",
        ),
        migrations.RemoveField(
            model_name="editingsession",
            name="ip_address",
        ),
        migrations.RemoveField(
            model_name="editingsession",
            name="user_agent",
        ),
        migrations.RemoveField(
            model_name="submission",
            name="auto_analyze_documents",
        ),
        migrations.RemoveField(
            model_name="submission",
            name="notify_on_analysis",
        ),
        migrations.RemoveField(
            model_name="templatefield",
            name="help_text",
        ),
        migrations.RemoveField(
            model_name="templatefield",
            name="placeholder",
        ),
        migrations.RemoveField(
            model_name="templatefield",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="templatefield",
            name="validation_pattern",
        ),
        migrations.AlterField(
            model_name="aianalysisresult",
            name="suggested_module",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="ctd_submission.ctdmodule",
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="submission_type",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="templatefield",
            name="field_type",
            field=models.CharField(
                choices=[
                    ("text", "Text Field"),
                    ("textarea", "Text Area"),
                    ("select", "Select Dropdown"),
                    ("checkbox", "Checkbox"),
                    ("number", "Number Field"),
                    ("date", "Date Field"),
                ],
                default="text",
                max_length=20,
            ),
        ),
    ]
