# Generated by Django 5.2.4 on 2025-07-29 00:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ctd_submission", "0007_alter_aianalysisresult_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aianalysisresult",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="ctdmodule",
            options={"ordering": ["code"]},
        ),
        migrations.AlterModelOptions(
            name="document",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="submission",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="aianalysisresult",
            name="analysis_method",
            field=models.CharField(default="traditional", max_length=50),
        ),
        migrations.AddField(
            model_name="aianalysisresult",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="templatefield",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="aianalysisresult",
            name="suggested_module",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="ctd_submission.ctdmodule",
            ),
        ),
        migrations.AlterField(
            model_name="documentversion",
            name="changes_summary",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="documentversion",
            name="content_data",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="documentversion",
            name="template_data",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="templatefield",
            name="field_type",
            field=models.CharField(
                choices=[
                    ("text", "Text Field"),
                    ("textarea", "Text Area"),
                    ("select", "Select Dropdown"),
                    ("checkbox", "Checkbox"),
                    ("number", "Number Field"),
                    ("date", "Date Field"),
                    ("email", "Email Field"),
                    ("url", "URL Field"),
                ],
                default="text",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="CollaborationSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.CharField(max_length=100, unique=True)),
                ("cursor_position", models.JSONField(default=dict)),
                ("active_element", models.CharField(blank=True, max_length=100)),
                ("last_activity", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collaboration_sessions",
                        to="ctd_submission.document",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-last_activity"],
            },
        ),
        migrations.CreateModel(
            name="DocumentAnnotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "annotation_type",
                    models.CharField(
                        choices=[
                            ("comment", "Commentaire"),
                            ("question", "Question"),
                            ("suggestion", "Suggestion"),
                            ("error", "Erreur"),
                            ("highlight", "Surlignage"),
                        ],
                        default="comment",
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                ("position_data", models.JSONField(default=dict)),
                ("selected_text", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_resolved", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="annotations",
                        to="ctd_submission.document",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_annotations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentProcessingLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "processing_type",
                    models.CharField(
                        choices=[
                            ("extraction", "Extraction de contenu"),
                            ("analysis", "Analyse IA"),
                            ("template_generation", "Génération de template"),
                            ("validation", "Validation"),
                            ("export", "Export"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("started", "Démarré"),
                            ("completed", "Terminé"),
                            ("failed", "Échoué"),
                        ],
                        max_length=20,
                    ),
                ),
                ("details", models.JSONField(default=dict)),
                ("error_message", models.TextField(blank=True)),
                ("processing_time", models.DurationField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="processing_logs",
                        to="ctd_submission.document",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserPreferences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "default_edit_mode",
                    models.CharField(
                        choices=[
                            ("text", "Texte"),
                            ("visual", "Visuel"),
                            ("structure", "Structure"),
                        ],
                        default="text",
                        max_length=20,
                    ),
                ),
                ("auto_save_enabled", models.BooleanField(default=True)),
                ("auto_save_interval", models.PositiveIntegerField(default=120)),
                ("copilot_enabled", models.BooleanField(default=True)),
                (
                    "copilot_sensitivity",
                    models.CharField(
                        choices=[
                            ("low", "Faible"),
                            ("medium", "Moyenne"),
                            ("high", "Élevée"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("collaboration_enabled", models.BooleanField(default=True)),
                (
                    "theme",
                    models.CharField(
                        choices=[
                            ("light", "Clair"),
                            ("dark", "Sombre"),
                            ("auto", "Automatique"),
                        ],
                        default="light",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="editor_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Préférences utilisateur",
                "verbose_name_plural": "Préférences utilisateur",
            },
        ),
        migrations.DeleteModel(
            name="EditingSession",
        ),
    ]
