# rawdocs/migrations/0001_initial.py
# Generated by Django 5.2.3 on 2025-06-18 09:16

from django.db import migrations, models
from django.conf import settings

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # s'assurer que le User est prêt avant de créer RawDocument
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RawDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField()),
                (
                    "file",
                    models.FileField(upload_to="%(Y)s%(m)s%(d)s_%(H)s%(M)s%(S)s/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        to=settings.AUTH_USER_MODEL,
                        on_delete=models.CASCADE,
                        related_name="raw_documents",
                    ),
                ),
            ],
        ),
    ]

