# Generated by Django 5.2 on 2025-06-26 16:54

import django.db.models.deletion
import rawdocs.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rawdocs", "0004_rawdocument_owner"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="rawdocument",
            name="file",
            field=models.FileField(
                help_text="Fichier PDF téléchargé",
                upload_to=rawdocs.models.pdf_upload_to,
            ),
        ),
        migrations.AlterField(
            model_name="rawdocument",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Utilisateur qui a téléchargé ce document",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="raw_documents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="rawdocument",
            name="url",
            field=models.URLField(help_text="URL d'origine du PDF"),
        ),
    ]
