# Generated by Django 5.2.3 on 2025-06-27 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rawdocs", "0005_alter_rawdocument_file_alter_rawdocument_owner_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="rawdocument",
            name="context",
            field=models.TextField(
                blank=True, help_text="Contexte extrait (2 phrases max)"
            ),
        ),
        migrations.AddField(
            model_name="rawdocument",
            name="country",
            field=models.CharField(
                blank=True,
                help_text="Pays détecté (GPE ou domaine TLD)",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="rawdocument",
            name="doc_type",
            field=models.CharField(
                blank=True,
                help_text="Type du document (guide, rapport, etc.)",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="rawdocument",
            name="language",
            field=models.CharField(
                blank=True, help_text="Langue détectée (fr, en...)", max_length=10
            ),
        ),
        migrations.AddField(
            model_name="rawdocument",
            name="publication_date",
            field=models.CharField(
                blank=True, help_text="Date de publication", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="rawdocument",
            name="source",
            field=models.CharField(
                blank=True,
                help_text="Nom de l'organisation (ex: EMA, FDA...)",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="rawdocument",
            name="title",
            field=models.TextField(blank=True, help_text="Titre du document"),
        ),
        migrations.AddField(
            model_name="rawdocument",
            name="version",
            field=models.CharField(
                blank=True, help_text="Version extraite", max_length=50
            ),
        ),
        migrations.CreateModel(
            name="MetadataLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_name", models.CharField(max_length=100)),
                ("old_value", models.TextField(blank=True, null=True)),
                ("new_value", models.TextField(blank=True, null=True)),
                ("modified_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rawdocs.rawdocument",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
