# Generated by Django 5.2 on 2025-07-17 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rawdocs", "0007_annotationtype_rawdocument_is_validated_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AILearningMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model_version",
                    models.CharField(default="groq_llama3.3_70b", max_length=50),
                ),
                ("precision_score", models.FloatField(default=0.0)),
                ("recall_score", models.FloatField(default=0.0)),
                ("f1_score", models.FloatField(default=0.0)),
                ("total_feedbacks", models.IntegerField(default=0)),
                ("improvement_rate", models.FloatField(default=0.0)),
                (
                    "entity_performance",
                    models.JSONField(
                        default=dict, help_text="Performance per entity type"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="PromptOptimization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entity_type", models.CharField(max_length=100)),
                ("optimized_prompt", models.TextField()),
                ("performance_score", models.FloatField()),
                ("feedback_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name="documentpage",
            name="human_validated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="documentpage",
            name="is_validated_by_human",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="documentpage",
            name="validated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="validated_pages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="AnnotationFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ai_annotations_before",
                    models.JSONField(
                        help_text="AI annotations before human correction"
                    ),
                ),
                (
                    "human_annotations_after",
                    models.JSONField(
                        help_text="Final annotations after human validation"
                    ),
                ),
                (
                    "corrections_made",
                    models.JSONField(
                        help_text="What was corrected: additions, deletions, modifications"
                    ),
                ),
                (
                    "feedback_score",
                    models.FloatField(
                        default=0.0, help_text="Overall feedback score (0-1)"
                    ),
                ),
                ("validated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "annotator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to="rawdocs.documentpage",
                    ),
                ),
            ],
            options={
                "unique_together": {("page", "annotator")},
            },
        ),
    ]
