# Generated by Django 5.2.3 on 2025-07-22 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rawdocs", "0008_ailearningmetrics_promptoptimization_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="annotation",
            name="source",
            field=models.CharField(
                choices=[
                    ("ai", "Intelligence Artificielle"),
                    ("manual", "Manuel"),
                    ("expert", "Expert"),
                ],
                default="ai",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="annotation",
            name="validated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="annotation",
            name="validation_status",
            field=models.CharField(
                choices=[
                    ("pending", "En attente"),
                    ("validated", "Validé"),
                    ("rejected", "Rejeté"),
                    ("expert_created", "Créé par expert"),
                ],
                default="pending",
                help_text="Statut de validation par l'expert",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="rawdocument",
            name="expert_ready_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Date à laquelle le document est devenu prêt pour l'expert",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="rawdocument",
            name="is_ready_for_expert",
            field=models.BooleanField(
                default=False, help_text="Document prêt pour révision expert"
            ),
        ),
    ]
