# Generated by Django 4.2.7 on 2025-08-10 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rawdocs', '0010_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('textarea', 'Long Text'), ('date', 'Date'), ('number', 'Number')], default='text', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rawdocs.rawdocument')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rawdocs.customfield')),
            ],
            options={
                'unique_together': {('document', 'field')},
            },
        ),
    ]
