# Generated by Django 5.2.3 on 2025-08-17 03:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rawdocs', '0011_customfield_customfieldvalue'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documentpage',
            name='critical_deadlines',
            field=models.JSONField(default=list, help_text='Délais critiques identifiés sur cette page'),
        ),
        migrations.AddField(
            model_name='documentpage',
            name='is_regulatory_analyzed',
            field=models.BooleanField(default=False, help_text="Page analysée par l'IA pour les aspects réglementaires"),
        ),
        migrations.AddField(
            model_name='documentpage',
            name='page_summary',
            field=models.TextField(blank=True, help_text='Résumé concis du contenu de la page'),
        ),
        migrations.AddField(
            model_name='documentpage',
            name='regulatory_analysis',
            field=models.JSONField(blank=True, help_text='Analyse réglementaire complète de la page par IA', null=True),
        ),
        migrations.AddField(
            model_name='documentpage',
            name='regulatory_analyzed_at',
            field=models.DateTimeField(blank=True, help_text="Date d'analyse réglementaire", null=True),
        ),
        migrations.AddField(
            model_name='documentpage',
            name='regulatory_analyzed_by',
            field=models.ForeignKey(blank=True, help_text="Utilisateur qui a lancé l'analyse réglementaire", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regulatory_analyzed_pages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentpage',
            name='regulatory_importance_score',
            field=models.IntegerField(default=0, help_text="Score d'importance réglementaire de cette page (0-100)"),
        ),
        migrations.AddField(
            model_name='documentpage',
            name='regulatory_obligations',
            field=models.JSONField(default=list, help_text='Liste des obligations réglementaires trouvées sur cette page'),
        ),
        migrations.CreateModel(
            name='DocumentRegulatoryAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('global_summary', models.TextField(blank=True, help_text='Résumé global du document complet')),
                ('consolidated_analysis', models.JSONField(default=dict, help_text='Analyse réglementaire consolidée de tout le document')),
                ('main_obligations', models.JSONField(default=list, help_text='Principales obligations réglementaires du document')),
                ('critical_deadlines_summary', models.JSONField(default=list, help_text='Résumé des délais critiques du document')),
                ('relevant_authorities', models.JSONField(default=list, help_text='Autorités réglementaires mentionnées dans le document')),
                ('global_regulatory_score', models.IntegerField(default=0, help_text="Score global d'importance réglementaire (0-100)")),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('total_pages_analyzed', models.IntegerField(default=0)),
                ('pages_with_regulatory_content', models.IntegerField(default=0)),
                ('analyzed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='regulatory_analysis', to='rawdocs.rawdocument')),
            ],
        ),
    ]
