# Generated by Django 5.2.3 on 2025-08-17 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rawdocs', '0012_documentpage_critical_deadlines_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentpage',
            name='annotations_json',
            field=models.JSONField(blank=True, help_text='JSON structuré de toutes les annotations de cette page', null=True),
        ),
        migrations.AddField(
            model_name='documentpage',
            name='annotations_summary',
            field=models.TextField(blank=True, help_text='Résumé en langage naturel des annotations de cette page'),
        ),
        migrations.AddField(
            model_name='documentpage',
            name='annotations_summary_generated_at',
            field=models.DateTimeField(blank=True, help_text="Date de génération du résumé d'annotations", null=True),
        ),
        migrations.AddField(
            model_name='rawdocument',
            name='global_annotations_json',
            field=models.JSONField(blank=True, help_text='JSON global consolidé de toutes les annotations du document', null=True),
        ),
        migrations.AddField(
            model_name='rawdocument',
            name='global_annotations_summary',
            field=models.TextField(blank=True, help_text='Résumé global en langage naturel des annotations du document'),
        ),
        migrations.AddField(
            model_name='rawdocument',
            name='global_annotations_summary_generated_at',
            field=models.DateTimeField(blank=True, help_text="Date de génération du résumé global d'annotations", null=True),
        ),
    ]
