# Generated by Django 5.2.3 on 2025-08-27 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rawdocs', '0014_metadatalearningmetrics_globalsummaryedithistory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawdocument',
            name='original_ai_metadata',
            field=models.JSONField(blank=True, help_text='Original AI extracted metadata for RLHF comparison', null=True),
        ),
    ]
