# Generated by Django 5.2.3 on 2025-08-29 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rawdocs', '0015_rawdocument_original_ai_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawdocument',
            name='expert_validated_at',
            field=models.DateTimeField(blank=True, help_text='Date de validation par un expert', null=True),
        ),
        migrations.AddField(
            model_name='rawdocument',
            name='is_expert_validated',
            field=models.BooleanField(default=False, help_text='Document validé par un expert'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('metadonneur', 'Métadonneur'), ('annotateur', 'Annotateur'), ('expert', 'Expert'), ('client', 'Client'), ('dev_metier', 'Dev métier')], default='client', max_length=20),
        ),
    ]
