# Generated by Django 5.2.3 on 2025-09-01 03:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rawdocs', '0016_rawdocument_expert_validated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documentpage',
            name='summary_validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='documentpage',
            name='summary_validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentpage',
            name='summary_validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_page_summaries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rawdocument',
            name='enriched_annotations_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rawdocument',
            name='enriched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rawdocument',
            name='enriched_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enriched_documents', to=settings.AUTH_USER_MODEL),
        ),
    ]
