# Generated by Django 5.2.3 on 2025-09-02 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rawdocs', '0017_documentpage_summary_validated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawdocument',
            name='structured_html',
            field=models.TextField(blank=True, help_text='HTML structuré fidèle au PDF (mise en page, tableaux, images)'),
        ),
        migrations.AddField(
            model_name='rawdocument',
            name='structured_html_confidence',
            field=models.FloatField(blank=True, help_text="Confiance globale de l'extraction", null=True),
        ),
        migrations.AddField(
            model_name='rawdocument',
            name='structured_html_generated_at',
            field=models.DateTimeField(blank=True, help_text='Date de génération du HTML structuré', null=True),
        ),
        migrations.AddField(
            model_name='rawdocument',
            name='structured_html_method',
            field=models.CharField(blank=True, help_text="Méthode d'extraction utilisée", max_length=100),
        ),
    ]
