# Generated by Django 4.2.7 on 2025-09-17 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('original_file', models.FileField(upload_to='uploads/%Y/%m/', verbose_name='Fichier original')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'Word Document'), ('doc', 'Word Document (Legacy)'), ('txt', 'Text File'), ('html', 'HTML File'), ('xlsx', 'Excel Spreadsheet'), ('xls', 'Excel Spreadsheet (Legacy)'), ('rtf', 'Rich Text Format')], max_length=10, verbose_name='Type de fichier')),
                ('file_size', models.BigIntegerField(verbose_name='Taille du fichier')),
                ('extracted_content', models.TextField(blank=True, null=True, verbose_name='Contenu extrait')),
                ('formatted_content', models.TextField(blank=True, null=True, verbose_name='Contenu formaté')),
                ('author', models.CharField(blank=True, max_length=255, null=True, verbose_name='Auteur')),
                ('creation_date', models.DateTimeField(blank=True, null=True, verbose_name='Date de création du document')),
                ('modification_date', models.DateTimeField(blank=True, null=True, verbose_name='Date de modification du document')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours de traitement'), ('completed', 'Traité'), ('error', 'Erreur')], default='pending', max_length=15, verbose_name='Statut')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Téléchargé le')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Traité le')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name="Message d'erreur")),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Téléchargé par')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/%Y/%m/', verbose_name='Image')),
                ('image_name', models.CharField(max_length=255, verbose_name="Nom de l'image")),
                ('position_in_document', models.IntegerField(verbose_name='Position dans le document')),
                ('width', models.IntegerField(blank=True, null=True, verbose_name='Largeur')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='Hauteur')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='documents.document')),
            ],
            options={
                'verbose_name': 'Image du document',
                'verbose_name_plural': 'Images des documents',
                'ordering': ['position_in_document'],
            },
        ),
        migrations.CreateModel(
            name='DocumentFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_width', models.FloatField(blank=True, null=True, verbose_name='Largeur de page')),
                ('page_height', models.FloatField(blank=True, null=True, verbose_name='Hauteur de page')),
                ('margins', models.JSONField(blank=True, null=True, verbose_name='Marges')),
                ('fonts_used', models.JSONField(blank=True, null=True, verbose_name='Polices utilisées')),
                ('has_headers', models.BooleanField(default=False, verbose_name='A des en-têtes')),
                ('has_footers', models.BooleanField(default=False, verbose_name='A des pieds de page')),
                ('has_tables', models.BooleanField(default=False, verbose_name='A des tableaux')),
                ('has_images', models.BooleanField(default=False, verbose_name='A des images')),
                ('generated_css', models.TextField(blank=True, null=True, verbose_name='CSS généré')),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='format_info', to='documents.document')),
            ],
            options={
                'verbose_name': 'Format du document',
                'verbose_name_plural': 'Formats des documents',
            },
        ),
    ]
