# Generated by Django 4.2.7 on 2025-07-15 11:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('autorisation', 'Autorisation initiale'), ('variation_ia', 'Variation Type IA'), ('variation_ib', 'Variation Type IB'), ('variation_ii', 'Variation Type II'), ('renouvellement', 'Renouvellement')], max_length=20, verbose_name='Type de soumission')),
                ('status', models.CharField(choices=[('en-cours', 'En cours'), ('approuve', 'Approuvé'), ('rejete', 'Rejeté'), ('en-attente', 'En attente')], default='en-cours', max_length=20)),
                ('submission_date', models.DateField(verbose_name='Date de soumission')),
                ('estimated_completion', models.DateField(verbose_name="Date d'achèvement estimée")),
                ('actual_completion', models.DateField(blank=True, null=True, verbose_name="Date d'achèvement réelle")),
                ('responsible', models.CharField(max_length=100, verbose_name='Responsable')),
                ('progress', models.IntegerField(default=0, verbose_name='Progression (%)')),
                ('team', models.CharField(blank=True, max_length=50, verbose_name='Équipe')),
                ('priority', models.CharField(default='normale', max_length=20, verbose_name='Priorité')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='products.product')),
            ],
            options={
                'verbose_name': 'Soumission réglementaire',
                'verbose_name_plural': 'Soumissions réglementaires',
                'ordering': ['-submission_date'],
            },
        ),
        migrations.CreateModel(
            name='ReportKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('period', models.CharField(default='30d', max_length=10)),
                ('total_submissions', models.IntegerField(default=0)),
                ('average_delay', models.FloatField(default=0.0)),
                ('success_rate', models.FloatField(default=0.0)),
                ('delayed_count', models.IntegerField(default=0)),
                ('submissions_trend', models.FloatField(default=0.0)),
                ('delay_trend', models.FloatField(default=0.0)),
                ('success_trend', models.FloatField(default=0.0)),
                ('delayed_trend', models.FloatField(default=0.0)),
                ('trend_data', models.JSONField(default=dict)),
                ('status_data', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'KPI Report',
                'verbose_name_plural': 'KPIs Reports',
                'unique_together': {('date', 'period')},
            },
        ),
        migrations.CreateModel(
            name='ReportHeatmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('authorization_delay', models.IntegerField(blank=True, null=True)),
                ('variation_delay', models.IntegerField(blank=True, null=True)),
                ('renewal_delay', models.IntegerField(blank=True, null=True)),
                ('authorization_status', models.CharField(default='good', max_length=10)),
                ('variation_status', models.CharField(default='good', max_length=10)),
                ('renewal_status', models.CharField(default='good', max_length=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'verbose_name': 'Heatmap Data',
                'verbose_name_plural': 'Heatmap Data',
                'unique_together': {('product', 'date')},
            },
        ),
    ]
